// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARuHtIMO9azJTFBVJRBgqdkEArINxTtoI',
    appId: '1:894998918101:web:44262a6de08cd9f7ff435c',
    messagingSenderId: '894998918101',
    projectId: 'ar-medidas',
    authDomain: 'ar-medidas.firebaseapp.com',
    storageBucket: 'ar-medidas.firebasestorage.app',
    measurementId: 'G-HKJ5LR412N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWmcTfX6cMQ4NYQBDlpzBd5G2E047lpuA',
    appId: '1:894998918101:android:ce47e84df5140a37ff435c',
    messagingSenderId: '894998918101',
    projectId: 'ar-medidas',
    storageBucket: 'ar-medidas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO4RSh9sUAC6rXJElaHv0AYmrGXSQCIpg',
    appId: '1:894998918101:ios:ab90f2a3bc0d9b46ff435c',
    messagingSenderId: '894998918101',
    projectId: 'ar-medidas',
    storageBucket: 'ar-medidas.firebasestorage.app',
    iosBundleId: 'com.example.arMedidas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO4RSh9sUAC6rXJElaHv0AYmrGXSQCIpg',
    appId: '1:894998918101:ios:ab90f2a3bc0d9b46ff435c',
    messagingSenderId: '894998918101',
    projectId: 'ar-medidas',
    storageBucket: 'ar-medidas.firebasestorage.app',
    iosBundleId: 'com.example.arMedidas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARuHtIMO9azJTFBVJRBgqdkEArINxTtoI',
    appId: '1:894998918101:web:ee7c776be0fb7795ff435c',
    messagingSenderId: '894998918101',
    projectId: 'ar-medidas',
    authDomain: 'ar-medidas.firebaseapp.com',
    storageBucket: 'ar-medidas.firebasestorage.app',
    measurementId: 'G-889B4X5YK6',
  );
}
