name: connectfeso
description: "Faça um Tour pelos campus do UNIFESO."



publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1



environment:
  sdk: ^3.7.0



dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  firebase_core: ^3.12.0  # Versão mais recente do firebase_core (verifique sempre no pub.dev)
  firebase_auth: ^5.5.0 # Versão mais recente do firebase_auth (verifique sempre no pub.dev)
  google_sign_in: ^6.2.2 # Versão mais recente do google_sign_in (verifique sempre no pub.dev)
  lottie: ^3.3.1
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.0
  flutter_speed_dial: ^7.0.0
  cupertino_icons: ^1.0.8
  panorama_viewer: ^2.0.4
  carousel_slider: ^5.1.1
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0




flutter_icons:
  android: true
  ios: true
  image_path: "assets/icone_connectfeso.png"  # caminho para sua imagem do ícone





flutter:
  uses-material-design: true

  assets:
    - assets/google.svg
    - assets/connectfeso.png
    - assets/feso_pulsando.json
    - assets/cadastro.png
    - assets/resetsenha.png
    - assets/connect_feso_branco.png
    - assets/connect_chat_branco.png
    - assets/marcador.png
    - assets/tour_360_branco_sem_fundo.png

    - assets/icone_360.png
    - assets/360-graus.png

    - assets/foto_fazenda.jpg
    - assets/foto_proarte.jpg
    - assets/foto_sede.jpg

    - assets/construcao.png

# imagens na pasta 360
    # sede
    - assets/360/sede/sede_fachada.jpg
    - assets/360/sede/patio_sede_relogio.jpg
    - assets/360/sede/patio_sede.jpg
    - assets/360/sede/sede_casarao.jpg

    #proarte
    - assets/360/proarte/proarte.jpg
    - assets/360/proarte/teste1.jpg

    #fazenda
    - assets/360/quinta_paraiso/teste1.jpg
    - assets/360/quinta_paraiso/teste2.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
