// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfrzsozbSHUSP1ZTJY2D_8T78IHTaqkc8',
    appId: '1:261992274173:android:75d44665a95fc4c06f4694',
    messagingSenderId: '261992274173',
    projectId: 'connectfeso',
    storageBucket: 'connectfeso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvAZQjHkTFMNXSoF0F7xYc5tAajKunOL0',
    appId: '1:261992274173:ios:e7e5c64e9e4e75656f4694',
    messagingSenderId: '261992274173',
    projectId: 'connectfeso',
    storageBucket: 'connectfeso.firebasestorage.app',
    androidClientId: '261992274173-n7nna677n7k81avjsp1bg73k80n0gvks.apps.googleusercontent.com',
    iosClientId: '261992274173-2r4hr4648ck5kogoet6f5pvicv3pj8nq.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectfeso',
  );

}