name: shop_ar
description: "Projeto de aplicativo mobile em Flutter para demonstração de móveis utilizando realidade aumentada."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  vector_math: ^2.1.0
  model_viewer_plus: ^1.9.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/
    - assets/images/

  fonts:
    - family: Poppins